name: Build Artifacts
description: 'Builds the artifacts for extension releases.'

permissions:
  contents: write
  discussions: write

runs:
  using: 'composite'
  steps:
    - name: Build
      shell: bash
      run: pnpm build

    - name: Tag
      step: v
      shell: bash
      run: echo "version=$(npm pkg get version | sed 's/"//g')" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.zip
        tag_name: ${{ steps.v.outputs.version }}
        body: |
          # Changelog
          Please see [CHANGELOG.md](https://github.com/hoverscan/blob/main/CHANGELOG.md) for more information on what has changed recently.
        draft: false
        prerelease: false
