curl -o fantom.svg https://www.ankr.com/rpc/static/media/ftm.c92e9c29.svg
curl -o gnosis.svg https://www.ankr.com/rpc/static/media/gnosis.682dc52c.svg
curl -o optimism.svg https://www.ankr.com/rpc/static/media/optimism.53b7f574.svg
curl -o polygon.svg https://www.ankr.com/rpc/static/media/polygon.a5e91b5d.svg
curl -o celo.svg https://www.ankr.com/rpc/static/media/celo.11c5d71f.svg
curl -o polygonZkEvm.svg https://www.ankr.com/rpc/static/media/polygon-zkevm.8c6d01fe.svg
curl -o zkSyncEra.svg https://www.ankr.com/rpc/static/media/zksync_era.3b74e542.svg
curl -o moonbeam.svg https://www.ankr.com/rpc/static/media/moonbeam.3983fccc.svg
curl -o harmonyOne.svg https://www.ankr.com/rpc/static/media/harmony.f8aabc90.svg
curl -o mantle.svg https://www.ankr.com/rpc/static/media/mantle.23c992b8.svg
curl -o metis.svg https://www.ankr.com/rpc/static/media/metis.77fe8764.svg
curl -o scroll.png https://www.ankr.com/rpc/static/media/scroll.88691238.png
curl -o opBNB.svg https://docs.bnbchain.org/opbnb-docs/img/logo.svg