import type { ALL_SUPPORTED_CHAINS } from './all'
import * as chains from './chains'

export const icons: Record<'default' | typeof ALL_SUPPORTED_CHAINS[number]['id'], string> = {
  default: require('data-base64:~assets/networks/default.png'),

  [chains.arbitrumNova.id]: require('data-base64:~assets/networks/arbitrumNova.svg'),
  [chains.arbitrumOne.id]: require('data-base64:~assets/networks/arbitrumOne.svg'),
  [chains.aurora.id]: require('data-base64:~assets/networks/aurora.png'),
  [chains.avalanche.id]: require('data-base64:~assets/networks/avalanche.svg'),
  [chains.base.id]: require('data-base64:~assets/networks/base.png'),
  [chains.boba.id]: require('data-base64:~assets/networks/boba.png'),
  [chains.bsc.id]: require('data-base64:~assets/networks/bsc.svg'),
  [chains.canto.id]: require('data-base64:~assets/networks/canto.svg'),
  [chains.celo.id]: require('data-base64:~assets/networks/celo.svg'),
  [chains.classic.id]: require('data-base64:~assets/networks/classic.png'),
  [chains.confluxESpace.id]: require('data-base64:~assets/networks/conflux.svg'),
  [chains.cronos.id]: require('data-base64:~assets/networks/cronos.png'),
  [chains.crossbell.id]: require('data-base64:~assets/networks/crossbell.png'),
  [chains.dogechain.id]: require('data-base64:~assets/networks/dogechain.png'),
  [chains.fantom.id]: require('data-base64:~assets/networks/fantom.svg'),
  [chains.gnosis.id]: require('data-base64:~assets/networks/gnosis.svg'),
  [chains.harmonyOne.id]: require('data-base64:~assets/networks/harmonyOne.svg'),
  [chains.linea.id]: require('data-base64:~assets/networks/linea.svg'),
  [chains.mainnet.id]: require('data-base64:~assets/networks/mainnet.svg'),
  [chains.mantle.id]: require('data-base64:~assets/networks/mantle.svg'),
  [chains.metis.id]: require('data-base64:~assets/networks/metis.svg'),
  [chains.moonbeam.id]: require('data-base64:~assets/networks/moonbeam.svg'),
  [chains.moonriver.id]: require('data-base64:~assets/networks/moonriver.png'),
  [chains.okc.id]: require('data-base64:~assets/networks/okc.png'),
  [chains.opBNB.id]: require('data-base64:~assets/networks/opBNB.svg'),
  [chains.optimism.id]: require('data-base64:~assets/networks/optimism.svg'),
  [chains.polygon.id]: require('data-base64:~assets/networks/polygon.svg'),
  [chains.polygonZkEvm.id]: require('data-base64:~assets/networks/polygonZkEvm.svg'),
  [chains.scroll.id]: require('data-base64:~assets/networks/scroll.png'),
  [chains.zkSyncEra.id]: require('data-base64:~assets/networks/zkSyncEra.svg'),
  [chains.zora.id]: require('data-base64:~assets/networks/zora.svg'),
}
