name: Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/**/*
      - package.json
      - pnpm-lock.yaml
      - '**.js'
      - '**.ts'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Install
        uses: './.github/actions/install-deps'

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
