name: Create Release PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Install
        uses: './.github/actions/install-deps'

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          commit: 'chore(changeset): bump version'
          title: 'chore(changeset): bump version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: ./.github/actions/build-artifacts
