name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - '*.*.*'

permissions:
  contents: write
  discussions: write

jobs:
  canary:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install
        uses: './.github/actions/install-deps'

      - name: Build
        run: pnpm build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
          body: |
            # Changelog
            Please see [CHANGELOG.md](https://github.com/hoverscan/blob/main/CHANGELOG.md) for more information on what has changed recently.
          draft: false
          prerelease: false
